version: "3.8"

volumes:
  mysql-data:


services:
  devcontainer:
    build: .
    expose:
      - 80
    volumes:
      - ../:/workspace:cached
      - ../:/var/www/html:cached

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
